[target.xtensa-esp32s3-none-elf]
# runner = "espflash flash --monitor --chip esp32s3"
runner = "espflash flash --monitor --partition-table ./partitions.csv --erase-parts otadata"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3"

[env]

[build]
# add in for esp32s3 again
#
rustflags = [
  # --- ADD following new flag ---
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
